version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../.devcontainer/Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/workspace:cached
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=info
    depends_on:
      - mlflow

  mlflow:
    image: python:3.11-slim
    working_dir: /mlflow
    volumes:
      - ./mlflow_data:/mlflow
    ports:
      - "5000:5000"
    command: >
      sh -c "pip install mlflow &&
             mlflow server --backend-store-uri sqlite:///mlflow.db
                           --default-artifact-root /mlflow/artifacts
                           --host 0.0.0.0 --port 5000"
