version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../.devcontainer/Dockerfile
    working_dir: /workspace/backend
    command: >
      python -m uvicorn app.main:app
      --host 0.0.0.0
      --port ${BACKEND_PORT}
      --reload
      --reload-dir app
      --reload-exclude /workspace/frontend/*
      --reload-exclude /workspace/backend/app/__pycache__/*
      --reload-exclude /workspace/.git/*
    volumes:
      - ./backend:/workspace/backend:cached
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      # Optionally, pass DATABASE_URL if your backend expects it
      # DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      MINIO_ENDPOINT: "http://minio:${MINIO_PORT:-9000}"
      MINIO_BUCKET: "${MINIO_BUCKET:-uhi}"
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
    depends_on:
      db:
        condition: service_started
      mlflow:
        condition: service_started
      minio:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: ../.devcontainer/Dockerfile
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "start"]
    depends_on:
      - backend

  pgadmin:
    image: dpage/pgadmin4:7.6
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"  # Enable pre-configured servers
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./scripts/pgadmin/generate_servers.sh:/scripts/pgadmin/generate_servers.sh
    #entrypoint: ["/bin/sh", "-c", "sh /scripts/pgadmin/generate_servers.sh && /entrypoint.sh"]

  db:
    image: postgis/postgis:15-3.4-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./scripts/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  mlflow:
    image: python:3.11-slim
    working_dir: /mlflow
    volumes:
      - ./mlflow_data:/mlflow
    ports:
      - "${MLFLOW_PORT}:5000"
    command: >
      sh -c "pip install mlflow &&
             mlflow server --backend-store-uri sqlite:///mlflow.db
                           --default-artifact-root /mlflow/artifacts
                           --host 0.0.0.0 --port ${MLFLOW_PORT}"

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":${MINIO_CONSOLE_PORT:-9001}"
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
    ports:
      - "${MINIO_PORT:-9000}:9000"                 # S3 API
      - "${MINIO_CONSOLE_PORT:-9001}:9001"         # Web-Konsole
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  pgadmin_data:
  minio_data:
